<?xml version="1.0" ?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


	<!-- Robot constants and properties -->
	<xacro:include filename="$(find my_robot_description)/urdf/my_robot_properties.xacro" />


	<joint name="camera_joint" type="fixed">
		<origin xyz="${-cameraSize+chassisLength/2} 0 ${cameraSize+wheelRadius+cameraSize/2}" rpy="0 0 0"/>
		<parent link="chassis"/>
		<child link="camera"/>
	</joint>

	<link name="camera">
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${cameraSize} 
						   ${cameraSize} 
						   ${cameraSize}"/>
			</geometry>
		</collision>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${cameraSize} 
						   ${cameraSize} 
						   ${cameraSize}"/>
			</geometry>
			<material name="blue"/>
		</visual>

		<inertial>
			<mass value="${cameraMass}" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<box_inertia m="${cameraMass}" 
						 x="${cameraSize}" 
						 y="${cameraSize}" 
						 z="${cameraSize}" />
		</inertial>
	</link>

</robot>